[package]
name = "wish_and_swish"
version = "0.1.1"
edition = "2021"
authors = ["Christian Mbaba"]

[dependencies]
cpal = "0.15.3"       # For audio output
sysfs_gpio = "0.6.2"  # For GPIO access/support
vosk = "0.3.1"        # For offline speech recognition
