# [target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = [
#   "probe-rs",
#   "run",
#   "--chip",
#   "nRF52833_xxAA",
#   "--log-format",
#   "{L} {s}",
# ]

# rustflags = [
#   "-C", "link-arg=-Tlink.x",
#   "-C", "link-arg=-Tdefmt.x",
# ]

[build]
target = "aarch64-unknown-linux-gnu"

# [env]
# DEFMT_LOG = "debug"