name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-03-12
          profile: minimal
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Install Dependencies
        run: |
          sudo apt install -y libclang-dev libasound2-dev
          rustup target add aarch64-unknown-linux-gnu
          rustup component add rustfmt clippy llvm-tools
          cargo install cargo-binutils

      - name: Run Linter
        run: cargo clippy --bin wish_and_swish -- -D warnings

      - name: Run Tests
        run: cargo test
      